// vue/src/App.vue
<script setup lang="ts">
import { ref, onMounted } from "vue";

// reactive state
const newTodo = ref("");
const todos = ref<string[]>([]);

const addTodo = () => {
  todos.value.push(newTodo.value);
  newTodo.value = "";
};

const removeTodo = (index: number) => {
  todos.value.splice(index, 1);
};

onMounted(() => {
  document.documentElement.style.setProperty("--app-color", "green");
});
</script>

<template>
  <div class="container">
    <h1>With <span class="app-color">Vue</span></h1>
    <input
      class="input"
      v-model="newTodo"
      placeholder="กรอก ...."
      @keyup.enter="addTodo"
    />
    <ul class="display">
      <li class="item" v-for="(todo, index) in todos" :key="index">
        {{ todo }}
        <button @click="removeTodo(index)">X</button>
      </li>
    </ul>
  </div>
</template>

<style scoped>
@import "../../core.css";
</style>

// react/src/App.tsx
import { useState, useEffect } from "react";

import "../../core.css";

function App() {
  const [todos, setTodos] = useState<string[]>([]);
  const [newTodo, setNewTodo] = useState("");

  const addTodo = (e: React.KeyboardEvent<HTMLInputElement>) => {
    e.preventDefault();

    if (e.code !== "Enter") return;

    setTodos([...todos, newTodo]);
    setNewTodo("");
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setNewTodo(e.target.value);
  };

  const removeTodo = (index: number) => {
    setTodos((prev) => [...prev.slice(0, index), ...prev.slice(index + 1)]);
  };

  useEffect(() => {
    document.documentElement.style.setProperty("--app-color", "cyan");
  });

  return (
    <div className="container">
      <h1>
        With <span className="app-color">React</span>
      </h1>
      <input
        className="input"
        value={newTodo}
        placeholder="กรอก ...."
        onKeyUp={addTodo}
        onChange={handleChange}
      />
      <ul className="display">
        {todos.map((todo, index) => (
          <li className="item" key={index}>
            {todo}
            <button onClick={() => removeTodo(index)}>X</button>
          </li>
        ))}
      </ul>
    </div>
  );
}

export default App;
